version: "3.3"
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: trytondb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: